name: 'ToDo App RealTime Development'
services:
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - BASE_URL=todo-api
    depends_on:
      - todo-api
      - chat-api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/son/src/FE-app
      - /son/src/FE-app/node_modules/

  chat-api:
    build:
      context: ./chat-api
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - mongo
    ports:
      - "3002:8080"
    volumes:
      - ./chat-api:/app
      - ~/.m2:/root/.m2
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://user:ns@mongo:27017/admin
      - SECRET_KEY=MySuperSecureJWTSecretKeyWhichIsAtLeast32Char

  todo-api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - postgres_app
    environment:
      - PORT=3001
      - DATABASE_PASSWORD=ns
      - BASE_URL=todo-api
      - DATABASE_HOST=postgres_app
    # secrets:
    #   - DATABASE_PASSWORD      
    volumes:
      - ./todo-api:/son/src/app
      - /son/src/app/node_modules/
    ports:
      - "3001:3001"
    command: ["npm", "run", "start:dev"]
  postgres_app:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=ns
      - JWT_SERECT=MySuperSecureJWTSecretKeyWhichIsAtLeast32Char
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=ns
      - MONGO_INITDB_DATABASE=chat
  
  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ns
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ns
    depends_on:
      - mongo
volumes:
  db_data:
  mongo_data:
# secrets:
#   DATABASE_PASSWORD:
#     file: ./todo-api/.env