apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: todosocket
# build:
  # artifacts:
  # - image: todosocket-fe
  #   context: frontend
  #   docker:
  #     dockerfile: Dockerfile.dev
  #   sync:
  #     manual:
  #       - src: frontend/src/**/*.js
  #         dest: son/src/FE-app/src
  #       - src: frontend/public/**/*
  #         dest: son/src/FE-app/public
  # - image: todosocket-chat-api
  #   context: chat-api
  #   docker:
  #     dockerfile: Dockerfile.dev
  #   sync:
  #     manual:
  #       - src: chat-api/src/main/**/*
  #         dest: app/src
    
  # - image: todosocket-todo-api
  #   context: todo-api
  #   docker:
  #     dockerfile: Dockerfile.dev
  #   sync:
  #     manual:
  #       - src: todo-api/src/**/*.ts
  #         dest: app/src
deploy:
  kubectl:
    flags:
      apply:
      - -f
      - k8s/config-secret/*.yaml
      - -f 
      - k8s/database/*.yaml
      - -f
      - k8s/app/*.yaml