apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-depl
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin-depl
        image: dpage/pgadmin4
        env: 
        - name: PGADMIN_DEFAULT_EMAIL
          value: son@gmail.com
          # valueFrom:
          #   configMapKeyRef:
          #     name: postgres-config
          #     key: POSTGRES_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pass
          # valueFrom:
          #   configMapKeyRef:
          #     name: postgres-config
          #     key: POSTGRES_PASSWORD
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer